In [5]:
pip install pandas

Collecting pandas
  Using cached pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
Collecting pytz>=2020.1
  Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Collecting tzdata>=2022.7
  Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:



import pandas as pd

column = ["Maria", "Batman", "Spongebob"]
titled_clolumns = {"name": column,
                  "height": [1.17, 1.9, 0.25],
                  "weight": [54, 100, 1]}
data = pd.DataFrame(titled_clolumns)
select_column = data["weight"][1]
select_row = data.iloc[1][1]
print(select_row)

1.9

/var/folders/06/96ldnc117tj7n6vht4j2tg9c0000gn/T/ipykernel_5141/1020184159.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  select_row = data.iloc[1][1]

Lesson start here:

In [9]:
# pandas is a powerful data manipulation in python
# it is build on top of numpy
# lets breifly explore numpy first

# creating a numpy arrey

import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Numpy arrey is:")
print(data)

# exemple wihtout libriary(numpy/pandas)
data_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print('\n list')

print(data_list)

Numpy arrey is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 list
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# What proble does pandas solve?

data = [{'name': 'Alis', 'age': 25, 'city': 'New York', 'Salary': 70000},
        {'name': 'Bob', 'age': 31, 'city': 'San Francisco', 'Salary': 80000},
        {'name': 'Charlie', 'age': 35, 'city': 'Los Angeless', 'Salary': 90000}]

# What if we want analys this data?
# Maybe look att average  salary or maybe findout people older than 30

total = 0
count = 0
for person in data:
    total += person['Salary']
    count += 1
average_salary = total / count

print('\n Average salary is', average_salary)

older_than_30 = []
for person in data:
    if person['age'] > 30:
        older_than_30.append(person)

print('\n People older than 30', older_than_30)

 Average salary is 80000.0

 People older than 30 [{'name': 'Bob', 'age': 31, 'city': 'San Francisco', 'Salary': 80000}, {'name': 'Charlie', 'age': 35, 'city': 'Los Angeless', 'Salary': 90000}]

In [13]:
import pandas as pd

df = pd.DataFrame(data)

print('\nDataFrame:')
print(df)

average_salary = df['salary'].mean()
older_than_30 = df[df['age']>30]

print('\n Average salary:', average_salary)
print('People older than 30:\n', older_than_30)

DataFrame:
      name  age           city  Salary
0     Alis   25       New York   70000
1      Bob   31  San Francisco   80000
2  Charlie   35   Los Angeless   90000

KeyError: 'salary'

In [14]:
df

      name  age           city  Salary
0     Alis   25       New York   70000
1      Bob   31  San Francisco   80000
2  Charlie   35   Los Angeless   90000

In [15]:
# Pandas is quite good att detecting "table-like" data in varous formats, and can create dataframes from that "table-like"-data

data = {'name': ['Alis', 'Bob', 'Charlie'],
      'age': [25, 31, 35],
      'city': ['New York', 'San Francisco', 'Los Angeles'],
      'salary': [70000, 80000, 90000]}

df = pd.DataFrame(data)

print('\nDataframe from dictionary of list:')

print(df)

Dataframe from dictionary of list:
      name  age           city  salary
0     Alis   25       New York   70000
1      Bob   31  San Francisco   80000
2  Charlie   35    Los Angeles   90000

In [16]:
# create dataframe from several lists

name = ['Alis', 'Bob', 'Charlie']
age = [25, 31, 35]
city = ['New York', 'San Francisco', 'Los Angeles']
salaries = [70000, 80000, 90000]

df_list = pd.DataFrame({'name': name,
                        'age': age,
                        'city': city,
                        'salary': salaries})

print('\nDataframe from several lists')

print(df_list)

Dataframe from several lists
      name  age           city  salary
0     Alis   25       New York   70000
1      Bob   31  San Francisco   80000
2  Charlie   35    Los Angeles   90000

In [17]:
# create dataframe from a csv file

df_csv = pd.read_csv('titanic.csv')

print('\nDataframe from csv file - titanic:')

df_csv.head()  # Display the first five raws of the dataframe
print('\nDataframe info:')
df_csv.info() #sommary of dataframe
df_csv.describe() # Gives statistical summary

Dataframe from csv file - titanic:

Dataframe info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Inspecting and manupilate dataframe

In [18]:
import pandas as pd
# with head we can inspect few rows(by default five if you don't customize it. like puting a number of choice)
first_ten = df_csv.head(10)

print('\nFirst 10 rows of dataframe:\n', first_ten)

#Tail is the first but from the bottom 

last_ten = df_csv.tail(10)

print('\nLast 10 rows of datframe is:', last_ten)

First 10 rows of dataframe:
    PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

Last 10 rows of datframe is:      PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann
882          883         0       3              Dahlberg, Miss. Gerda Ulrika
883          884         0       2             Banfield, Mr. Frederick James
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
881    male  33.0      0      0            349257   7.8958   NaN        S
882  female  22.0      0      0              7552  10.5167   NaN        S
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
885  female  39.0      0      5            382652  29.1250   NaN        Q
886    male  27.0      0      0            211536  13.0000   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0            111369  30.0000  C148        C
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [19]:
# Selecting colon

print('\nNam colon is:\n', df_csv)
print('\nNames and ages colon:', df_csv[['Name', 'Age']])

# select the rows by index

print('\nRow at index 0:\n', df_csv.iloc[0])
# Seclect mutiple rows 

print('\nRows at index 0 and 4\n', df_csv.iloc[0:5])

Nam colon is:
      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

Names and ages colon:                                                   Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

Row at index 0:
 PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

Rows at index 0 and 4
    PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [20]:
# Finding conditions in dataframes uses a condition 
# The condition returns the boolians series, wich is then used to filter the dataframe
# the boolians series can be thought of as big list, with True/False for each row in dataframe
# True where the condition is met,  False otherwise

# We ther use that list to find all the rows where the condition True

adults = df_csv[df_csv['Age']>=18]
print('\nAdults age >=18', adults )

women = df_csv[df_csv['Sex'] == 'female']

print('\nWomen on the Titanic', women)

Adults age >=18      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
885          886         0       3
886          887         0       2
887          888         1       1
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
885      5            382652  29.1250   NaN        Q
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[601 rows x 12 columns]

Women on the Titanic      PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
880          881         1       2
882          883         0       3
885          886         0       3
887          888         1       1
888          889         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
880      1            230433  26.0000   NaN        S
882      0              7552  10.5167   NaN        S
885      5            382652  29.1250   NaN        Q
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S

[314 rows x 12 columns]

Adding new colomns and new rows/data

In [21]:
# Lets add a nw column "bonus" to the datafrme
# The Bonus is 10% of the salary

df['Bonus'] = df['salary']*0.12
print('\nDataframe with bonus column:')
print(df)

# Modify existing column

df['age'] = df['age'] + 1

print('\nDataframe with modified column')
print(df)

new_person = {'name': 'David', 'age': 28, 'city': 'Chicago', 'salary': 75000, 'Bonus': 90000}
df = pd.concat([df, pd.DataFrame([new_person])], ignore_index=True)
print('\nDataframe after adding new row ')
print(df)

Dataframe with bonus column:
      name  age           city  salary    Bonus
0     Alis   25       New York   70000   8400.0
1      Bob   31  San Francisco   80000   9600.0
2  Charlie   35    Los Angeles   90000  10800.0

Dataframe with modified column
      name  age           city  salary    Bonus
0     Alis   26       New York   70000   8400.0
1      Bob   32  San Francisco   80000   9600.0
2  Charlie   36    Los Angeles   90000  10800.0

Dataframe after adding new row
      name  age           city  salary    Bonus
0     Alis   26       New York   70000   8400.0
1      Bob   32  San Francisco   80000   9600.0
2  Charlie   36    Los Angeles   90000  10800.0
3    David   28        Chicago   75000  90000.0

Lesson 11

Data cleaning with pandas: Handling Missing Data, Duplicat and Data transformation
Paandas is very powerful for cleaning and data manupilation

In [32]:
data_with_nan = {
    'name': ['Alis', 'Bob', 'Charlie', None, 'Eve'],
    'age': [25, None, 35, 28, 32],
    'city': ['New York', 'London', None, 'Paris', 'Sydney'],
    'salary': [50000, 60000, 70000, 55000, None]
}

df_nan = pd.DataFrame(data_with_nan)
print('\nDataframe with nan is:')
print(df_nan)


# Check for missing values

print('\nMissing values in each column:\n', df_nan.isnull().sum())


# Fill missing values
# we fill missing values with fillna()-method
df_filled = df_nan.fillna({
    'name': 'Unknow',
    'age': df_nan['age'].mean(),
    'city': 'Unknown',
    'salary': df_nan['salary'].mean()
})

print('\nDataFrame after filling missing values:\n', df_filled)

# Drop rows with missing values

df_dropped = df_nan.dropna()
print('\nDataFrame after dropping rows with missing values:\n', df_dropped)

Dataframe with nan is:
      name   age      city   salary
0     Alis  25.0  New York  50000.0
1      Bob   NaN    London  60000.0
2  Charlie  35.0      None  70000.0
3     None  28.0     Paris  55000.0
4      Eve  32.0    Sydney      NaN

Missing values in each column:
 name      1
age       1
city      1
salary    1
dtype: int64

DataFrame after filling missing values:
       name   age      city   salary
0     Alis  25.0  New York  50000.0
1      Bob  30.0    London  60000.0
2  Charlie  35.0   Unknown  70000.0
3   Unknow  28.0     Paris  55000.0
4      Eve  32.0    Sydney  58750.0

DataFrame after dropping rows with missing values:
    name   age      city   salary
0  Alis  25.0  New York  50000.0

In [33]:
# isnull find all the NaN+None in the DataFrame
print(df_nan.isnull())

# Then we can use sum() to count the number True values in each column
print('\nCount of missing values in each column:\n', df_nan.isnull().sum())

    name    age   city  salary
0  False  False  False   False
1  False   True  False   False
2  False  False   True   False
3   True  False  False   False
4  False  False  False    True

Count of missing values in each column:
 name      1
age       1
city      1
salary    1
dtype: int64

Sorting/Filtering Data
Teacher recommandation: use pandas alot (kind 20h or what i can)

In [45]:
# Sorting by a single column

print('Sorted by age:\n', df_filled.sort_values(by='age') )

print('Sorted by salary Descending:\n', df_filled.sort_values(by='salary', ascending=False) )

# Multiple criteria sorting 
print('\nSorted by city, then by age:\n', df_filled.sort_values(by=['city', 'age']))

# Complex filtering using multiple boolean conditions
print('High earning adults in their 30s:\n', df_filled[(df_filled['age'] >=30) & (df_filled['salary'] >= 60000)])

Sorted by age:
       name   age      city   salary
0     Alis  25.0  New York  50000.0
3   Unknow  28.0     Paris  55000.0
1      Bob  30.0    London  60000.0
4      Eve  32.0    Sydney  58750.0
2  Charlie  35.0   Unknown  70000.0
Sorted by salary Descending:
       name   age      city   salary
2  Charlie  35.0   Unknown  70000.0
1      Bob  30.0    London  60000.0
4      Eve  32.0    Sydney  58750.0
3   Unknow  28.0     Paris  55000.0
0     Alis  25.0  New York  50000.0

Sorted by city, then by age:
       name   age      city   salary
1      Bob  30.0    London  60000.0
0     Alis  25.0  New York  50000.0
3   Unknow  28.0     Paris  55000.0
4      Eve  32.0    Sydney  58750.0
2  Charlie  35.0   Unknown  70000.0
High earning adults in their 30s:
       name   age     city   salary
1      Bob  30.0   London  60000.0
2  Charlie  35.0  Unknown  70000.0

In [49]:
# Add some more New yorkan

new_people = [
    {'name':'Fank', 'age': 20, 'city': 'New York', 'salary': 72000},
    {'name': 'Grace', 'age': 34, 'city': 'New York', 'Salary': 85000}
]

df_new = pd.DataFrame(new_people)
df_filled = pd.concat([df_filled, df_new], ignore_index=True)

Grouping Aggregating Data

In [58]:
print(df_filled)

city_group = df_filled.groupby('city')

city_group['salary'].mean()

city_stats = df_filled.groupby('city').agg({
    'age': ['mean', 'min', 'max'],
    'salary': ['mean', 'sum', 'count']
})

print('\nCity-wise statistics:\n', city_stats)

       name   age      city   salary   Salary
0      Alis  25.0  New York  50000.0      NaN
1       Bob  30.0    London  60000.0      NaN
2   Charlie  35.0   Unknown  70000.0      NaN
3    Unknow  28.0     Paris  55000.0      NaN
4       Eve  32.0    Sydney  58750.0      NaN
5      Fank  20.0  New York  72000.0      NaN
6     Grace  34.0  New York      NaN  85000.0
7      Fank  20.0  New York  72000.0      NaN
8     Grace  34.0  New York      NaN  85000.0
9      Fank  20.0  New York  72000.0      NaN
10    Grace  34.0  New York      NaN  85000.0

City-wise statistics:
                 age               salary
               mean   min   max     mean       sum count
city
London    30.000000  30.0  30.0  60000.0   60000.0     1
New York  26.714286  20.0  34.0  66500.0  266000.0     4
Paris     28.000000  28.0  28.0  55000.0   55000.0     1
Sydney    32.000000  32.0  32.0  58750.0   58750.0     1
Unknown   35.000000  35.0  35.0  70000.0   70000.0     1

In [59]:
# create a student grades dataset

np.random.seed(42) # For reproductible results

students_data = {
    'Student_ID': range(1, 11),
    'Name': np.random.randint(50, 100, 10),
    'Math': np.random.randint(50, 100, 10),
    'Science': np.random.randint(50, 100, 10),
    'English': np.random.randint(50, 100, 10)
}